Feature/game iterations
AntoineGonzalez/gameoflife pull request #5
Opened 2022-09-20 14:44 UTC by AntoineGonzalez

2022-09-21 10:06 UTC, jaljo requested changes

2022-09-21 10:06 UTC, jaljo commented on src/App.tsx
> +          <li>Nombre d&apos;itérations : {gameState.iterationCounter}</li>
Pourquoi tu as un caractere ascii ici ?

2022-09-21 10:06 UTC, jaljo commented on src/App.tsx
> +    <AppContainer className="App">
les classes sont plutot en snake-case en général

2022-09-21 10:06 UTC, jaljo commented on src/App.tsx
> +            </Button>
Ca serait mieux d'avoir un selecteur `selectIsRunning` qui te renvoie directement ce boolean. Ca t'eviterais une duplication et on prefere toujours avoir les selecteurs les plusa tomiques possibles pour qu'ils soient réutilisables et composable plus facilement

https://redux-toolkit.js.org/api/createSelector

2022-09-21 10:06 UTC, jaljo commented on src/App.tsx
> +    )
Alors ca, ca va pas être possible, par contre :D 

Même si rien ne t'en empêche (et c'est une aberration que react permette de faire ca), tu ne devrais **JAMAIS** utiliser le hook use state pour stocker autre chose que de valeurs scalaires (integers, booleans, objets litteraux).

Dans le monde merveilleux de javascript si tu commence a stocker des références a des fonctions, tu as pas fini de galérer avec des problèmes de perfs. C'est mineur a cette échelle de projet, mais réellement probématique des lors que tu commence a bosser sur des projets d'envergure, avec des sets de donnés conséquents. 

L'idée de base est la bonne, c'est juste pas implémenté de la bonne manière. Il vaudrait mieux avoir un ptit state interne pour savoir si le jeu a démarré:

```javascript
const [isStarted, setIsStarted] = useState<boolean> =(false)
```

Et utiliser ca de pair avec un hook d'effet, quelque chose du genre

```javascript
useEffect(() => {
  if(isStarted) {
    // set interval
  } else {
    // clear interval
  }
}, [isStarted])
```

2022-09-21 10:06 UTC, jaljo commented on src/components/Cell.tsx
> +  background-color: ${(props) => props.isAlive ? 'white' : 'grey'};
Juste pour info, tu peux aussi configurer styleint sur ton projet pour eviter d'avoir des inconcistances de style dans ton css / sass

2022-09-21 10:06 UTC, jaljo commented on src/components/Grid.tsx
> +
pourquoi une ligne vide ici ?

2022-09-21 10:06 UTC, jaljo commented on src/components/Grid.tsx
> +    }
meme remarque que précédemment, tu pourrais réutilsier ton selecteur `selectIsRunning`

2022-09-21 10:06 UTC, jaljo commented on src/store/slices/gameSlice.ts
> +const getCellNeighboursValues = (state: GameState, { x, y }: Coord) => {
Tu pourrais lui passer juste la grille en premier argument, non ? Ca sert a quoi te lui filer tout le state ?

2022-09-21 10:06 UTC, jaljo commented on src/store/slices/gameSlice.ts
> +        ).filter((value) => value).length
a quoi sert ton filter ? c'esta ssez cryptique a premiere vue

2022-09-21 10:06 UTC, jaljo commented on src/store/slices/gameSlice.ts
> +    },
bwof :/
Ptet plutot 

```javascript
tick: (state) => ({
   ...state,
  iterationCounter: state.iterationCounter++,
  grid: computeNewGrid()
})
```

2022-09-21 10:06 UTC, jaljo commented on src/store/slices/gameSlice.ts
> +    ...state,
cette fonction fait 500 trucs. Elle devrait juste, a mon sens, s'occuper de recalculer la grille. Sort la lofique d'incrémentation de ton compteur, et met la directement dans le reducer. Ca sera plus lisible, et plus facile a tester.

2022-09-21 10:15 UTC, AntoineGonzalez commented on src/App.tsx
> +          <li>Nombre d&apos;itérations : {gameState.iterationCounter}</li>
Règle eslint
![Capture d’écran du 2022-09-21 12-14-53](https://user-images.githubusercontent.com/45924026/191479095-e51cfd8f-a73c-47e4-92cc-d0ee6122f7e2.png)

2022-09-21 10:16 UTC, AntoineGonzalez commented on src/App.tsx
> +    <AppContainer className="App">
Class auto générée il me semble

2022-09-21 11:56 UTC, AntoineGonzalez commented on src/store/slices/gameSlice.ts
> +        ).filter((value) => value).length
La méthode `getCellNeighboursValues ` permet de récupérer  un tableaux de boolean contenant les valeurs des 8 voisins d'une cellule. Mon filter permet de garder uniquement les valeurs positives afin de compter les cellules voisines en vies.

2022-09-21 11:57 UTC, AntoineGonzalez commented on src/store/slices/gameSlice.ts
> +        ).filter((value) => value).length
J'ai rename `value` par `isAlive` pour rendre plus explicite ce filter

2022-09-22 08:25 UTC, jaljo requested changes

2022-09-22 08:25 UTC, jaljo commented on src/components/Grid.tsx
> +
:duck:

2022-09-22 08:38 UTC, jaljo approved these changes

2022-09-22 08:52 UTC, merged