pattern insertion
AntoineGonzalez/gameoflife pull request #6
Opened 2022-09-22 09:28 UTC by AntoineGonzalez

Add a list of patterns

2022-09-26 07:06 UTC, jaljo requested changes

2022-09-26 07:06 UTC, jaljo commented on src/components/Grid.tsx
> +  const selectedPattern = useSelector(selectSelectedPattern)
Un peu chelou comme nom de selecteur... `selectUserPattern` ou ptet juste `selectPattern` avec une valeur de pattern renvoyée par defaut ? C'est ce qu'il y aurait de plus simple IMHO

2022-09-26 07:06 UTC, jaljo commented on src/components/Grid.tsx
> +    }
il me semble que tu peux simplifier en if(selectPattern) {} car un nullable va toujours valoir false en JS

2022-09-26 07:06 UTC, jaljo commented on src/components/PatternList.tsx
> +  const selectedPattern = useSelector(selectSelectedPattern)
meme remarque que plus haut du coup.

2022-09-26 07:06 UTC, jaljo commented on src/components/PatternList.tsx
> +  const handlePatternClick = (pattern: PatternType) => {
Attention au nom de ce type. C'est deja un type TS, donc le suffixe "type" ne done aucune indication sur ce que tu manipule. Soit tu le vire (Pattern peut s'entendre, comme type), soit tu trouves quelques chose de plus parlant porteur d'un veritable sens dans ton application

2022-09-26 07:06 UTC, jaljo commented on src/store/slices/gameSlice.ts
> +      }
`if (!state.selectedPattern) { ... }`

2022-09-26 07:06 UTC, jaljo commented on src/store/slices/patternSlice.ts
> +export const initialState: PatternsState = [
Meme memarque ici? Ton suffise state est une indication technique. Elle ne donnce pas d'indication precise sur ce que tu manipule d'un poit de vue métier.

2022-09-26 07:06 UTC, jaljo commented on src/store/slices/patternSlice.ts
> +export default patternsSlice
Pourquoi mettre tout ca dans un slice ? En fin de compte ces patterns n'ont as besoin d'interagir avec des actions de ton app. Tu peux donc juste les mettre dans un fichier js a part sous forme de constante et les récupérer au besoin pour qu'ils soient consomés par tes composants

2022-09-26 07:59 UTC, AntoineGonzalez commented on src/components/Grid.tsx
> +    }
ESlint 
![Capture d’écran du 2022-09-26 09-58-52](https://user-images.githubusercontent.com/45924026/192224036-6eda93b4-0758-41b5-8192-d414de110528.png)

2022-09-26 08:02 UTC, AntoineGonzalez commented on src/components/PatternList.tsx
> +  const handlePatternClick = (pattern: PatternType) => {
J'avais fait un composant atomic Pattern.tsx que j'ai enlevé. Du coup j'avais un conflit entre Pattern (le composant) et Pattern (le type). J'avais donc mis l'alias PatternType sur le type pour les différencier.

2022-09-26 08:03 UTC, AntoineGonzalez commented on src/store/slices/gameSlice.ts
> +      }
ESlint comme au dessus

2022-09-26 08:12 UTC, AntoineGonzalez commented on src/store/slices/patternSlice.ts
> +export default patternsSlice
En codant cette partie j'avais en tête de pouvoir manipuler la liste de pattern depuis l'application (ajout et retrait) donc je me suis dis que ça devais être dans un slice. A voir si je dois changer ça en sachant que je ne vais pas le faire au final.

2022-09-26 08:18 UTC, AntoineGonzalez commented on src/components/Grid.tsx
> +    }
Dois-je supprimer la règle ?

2022-09-27 14:51 UTC, jaljo approved these changes

2022-09-27 15:36 UTC, merged